name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools

      - name: Build packages
        run: npm run build

      - name: Build ISO
        run: |
          cd packages/iso-builder
          sudo npm run build:iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nestos-iso
          path: packages/iso-builder/build/nestos.iso
          retention-days: 7

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Control Panel
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/control-panel/Dockerfile.dev
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/control-panel:latest
            ghcr.io/${{ env.REPO_LOWER }}/control-panel:${{ github.sha }}

      - name: Build and push System Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/system-service/Dockerfile.dev
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/system-service:latest
            ghcr.io/${{ env.REPO_LOWER }}/system-service:${{ github.sha }}
